### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by qhyun2** [qhyun2/Watch-Mega#4]
### High Priority
- [x] better mobile support
  - [x] double tap to seek
- [x] proper disposing of vjs player
- [x] fix volume slider
- [x] fix captions button not visible
- [x] reset video progress when loading a new video
- [x] track video progress based on filename

### Todo
- [ ] restructure to unified backend
- [ ] overhaul sync system
  - [ ] new person joining resets youtube video progress
  - [ ] ready feature
  - [ ] handle socket disconnect
- [x] proper uploading
- [x] mobile support
- [x] volume indicator
- [x] disable focus on fullscreen button
